spring:
  datasource:
    url: "jdbc:h2:file:~/data/liquibase"
    driverClassName: org.h2.Driver
    username: "sa"
    password:
  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.xml

  h2:
    console:
      enabled: true
      settings:
        trace: false

